"use strict";
exports.__esModule = true;
var Notebook_1 = require("./models/Notebook");
var Note_1 = require("./models/Note");
var Author_1 = require("./models/Author");
var author = new Author_1.Author();
author.setId(String(Date.now()));
author.setFirstName("Julio");
author.setLastName("Romero");
author.setNacionality("Argentina");
author.setAge(40);
var note1 = new Note_1.Note();
note1.setId("1");
note1.setTitle("Make English homework");
note1.setDescription("I've to resolve the page 24 of workbook");
note1.setCategory("homework");
var note2 = new Note_1.Note();
note2.setId("2");
note2.setTitle("Shopping for the week");
note2.setDescription("I've to buy food for the week");
note2.setCategory("homework");
var note3 = new Note_1.Note();
note3.setId("3");
note3.setTitle("Make English homework");
note3.setDescription("I've to resolve the page 24 of workbook");
note3.setCategory("home todo");
var note4 = new Note_1.Note();
note4.setId("4");
note4.setTitle("Clean the garage");
note4.setDescription("I've to clean the garage before Friday");
note4.setCategory("home todo");
var note5 = new Note_1.Note();
note5.setId("5");
note5.setTitle("Walking the dog");
note5.setDescription("I don't have to forget to walk the dog today");
note5.setCategory("home todo");
var myNotebook = new Notebook_1.Notebook();
myNotebook.setId(String(Date.now()));
myNotebook.setAuthor(author);
myNotebook.addNote(note1);
myNotebook.addNote(note2);
myNotebook.addNote(note3);
myNotebook.addNote(note4);
myNotebook.addNote(note5);
console.log(myNotebook);
var homeworks = myNotebook.filterNotesByCategory("homework");
console.log("Homeworks: ", homeworks);
var homeToDo = myNotebook.filterNotesByCategory("home todo");
console.log("Home to do: ", homeToDo);
